from src.domain.entities import ExtractorConfigData

UNKNOWN_OWNER = "Unknown"
UNKNOWN_BANK = "Unknown"
UNKNOWN_ACCOUNT = "000000000000000000"
CLABE_LENGTH = 18

BANK_DICT_KUSHKI = {
    "ABC CAPITAL": "0001",
    "ACTINVER": "0002",
    "AFIRME": "0003",
    "AKALA": "0004",
    "ALTERNATIVOS": "0091",
    "ARCUS": "0005",
    "ASP INTEGRA OPC": "0006",
    "AUTOFIN": "0007",
    "AZTECA": "0008",
    "BAJIO": "0009",
    "BANAMEX": "0010",
    "BANCO FINTERRA": "0011",
    "BANCO S3": "0012",
    "BANCOMEXT": "0013",
    "BANCOPPEL": "0014",
    "BANCREA": "0015",
    "BANJERCITO": "0016",
    "BANK OF AMERICA": "0017",
    "BANKAOOL": "0018",
    "BANOBRAS": "0019",
    "BANORTE": "0020",
    "BANREGIO": "0021",
    "BANSEFI": "0022",
    "BANSI": "0023",
    "BANXICO": "0024",
    "BARCLAYS": "0025",
    "BBASE": "0026",
    "BBVA MEXICO": "0027",
    "BMONEX": "0028",
    "CAJA POP MEXICA": "0029",
    "CAJA TELEFONIST": "0030",
    "CB INTERCAM": "0031",
    "CI BOLSA": "0032",
    "CIBANCO": "0033",
    "COMPARTAMOS": "0034",
    "CONSUBANCO": "0035",
    "CREDICAPITAL": "0036",
    "CREDIT SUISSE": "0037",
    "CRISTOBAL COLON": "0038",
    "CoDi Valida": "0039",
    "DONDE": "0040",
    "EVERCORE": "0041",
    "FINAMEX": "0042",
    "FINCOMUN": "0043",
    "FOMPED": "0044",
    "FONDO (FIRA)": "0045",
    "GBM": "0046",
    "GEM - STP": "0090",
    "HIPOTECARIA FED": "0047",
    "HSBC": "0048",
    "ICBC": "0049",
    "INBURSA": "0050",
    "INDEVAL": "0051",
    "INMOBILIARIO": "0052",
    "INTERCAM BANCO": "0053",
    "INVERCAP": "0054",
    "INVEX": "0055",
    "JP MORGAN": "0056",
    "KUSPIT": "0057",
    "LIBERTAD": "0058",
    "MASARI": "0059",
    "MIFEL": "0060",
    "MIZUHO BANK": "0061",
    "MONEXCB": "0062",
    "MUFG": "0063",
    "MULTIVA BANCO": "0064",
    "MULTIVA CBOLSA": "0065",
    "NAFIN": "0066",
    "PAGATODO": "0067",
    "PROFUTURO": "0068",
    "REFORMA": "0069",
    "SABADELL": "0070",
    "SANTANDER": "0071",
    "SCOTIABANK": "0072",
    "SHINHAN": "0073",
    "STP": "0074",
    "TRANSFER": "0075",
    "UNAGRA": "0076",
    "VALMEX": "0077",
    "VALUE": "0078",
    "VE POR MAS": "0079",
    "VECTOR": "0080",
    "VOLKSWAGEN": "0081",
}

DEFAULT_RECEIPT_EXTRACTOR = ExtractorConfigData(
    id=None,
    name="Boletas y recibos",
    description="Extrae información de boletas, recibos de compra y tickets de venta",
    prompt=(
        "Extrae la información de esta boleta o recibo de compra. "
        "Si algún campo no está presente en el documento, devuelve null para ese campo. "
        "Para los productos, extrae cada línea con su nombre, cantidad y precio unitario."
    ),
    model="claude-haiku-4-5-20251001",
    output_schema={
        "type": "object",
        "properties": {
            "comercio": {
                "type": "string",
                "description": "Nombre del comercio o negocio",
            },
            "fecha": {
                "type": "string",
                "description": "Fecha de la compra (formato YYYY-MM-DD)",
            },
            "productos": {
                "type": "array",
                "description": "Lista de productos o servicios",
                "items": {
                    "type": "object",
                    "properties": {
                        "nombre": {
                            "type": "string",
                            "description": "Nombre del producto o servicio",
                        },
                        "cantidad": {
                            "type": "number",
                            "description": "Cantidad comprada",
                        },
                        "precio_unitario": {
                            "type": "number",
                            "description": "Precio por unidad",
                        },
                    },
                    "required": ["nombre", "cantidad", "precio_unitario"],
                },
            },
            "subtotal": {
                "type": "number",
                "description": "Subtotal antes de impuestos",
            },
            "impuesto": {
                "type": "number",
                "description": "Monto del impuesto (IVA u otro)",
            },
            "total": {
                "type": "number",
                "description": "Total de la compra",
            },
            "metodo_pago": {
                "type": "string",
                "description": "Método de pago (efectivo, tarjeta, etc.)",
            },
        },
        "required": ["comercio", "fecha", "total"],
    },
    is_default=True,
    status="active",
)
